### ISSUE TITLE
作者您好！希望向您询问相关疑惑

### ISSUE THREAD

**Issue by IntegralCoCo** [1170300521/DiFa#2]
这是一篇非常优秀的文章，我看完后感觉非常令人受启发，因此想follow您的工作，在此之前，我有一个相关疑惑，就是在文章3.3中的“Intuitively, if an attribute is similar between domains A and B during adaption, it is more likely to be a domain-sharing attribute.”我想请问您在开始您文章的实验之前，有提前做实验之类的验证过这个假设吗，或是有相关的工作探讨过这个问题吗 (直觉上有点像domian gap相关)，我的邮件是1092944263@qq.com，万分期待您的回复，与您进行学术相关的探讨，也期盼与您合作。

**Comment by YBYBZhang** [comment]
谢谢您对我们工作的关注！之前有相关工作做过类似假设，比如说StyleGAN-NADA中利用layer-freezing mechanism(Sec. 4.3) 通过latent code的变化程度，判断两个domain间差别较大的层，并进行优化。
也非常期待与您合作，联系方式邮件发您 !
